app = "voice-backend"
primary_region = "iad"

[build]

[env]
  PORT = "8080"
  SPRING_PROFILES_ACTIVE = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/api/voice-interaction/health"
  protocol = "http"
  timeout = "2s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "voice_data"
  destination = "/app/vector-store" 