[providers]
java = "21"

[phases.build]
dependsOn = ["install"]

[phases.install]
cmds = ["mvn dependency:go-offline -B"]

[phases.build.cmd]
cmd = "mvn clean package -DskipTests && mkdir -p vector-store user-data tts-cache"

[start]
cmd = "java -Dspring.profiles.active=production -Dserver.port=$PORT -Djava.security.egd=file:/dev/./urandom -Xms256m -Xmx512m -jar target/voice-detection-1.0-SNAPSHOT.jar"

[variables]
JAVA_VERSION = "21"
MAVEN_OPTS = "-Xmx1024m"
SPRING_PROFILES_ACTIVE = "production" 